### ISSUE TITLE
Multiple Fieds, priority

### ISSUE THREAD

**Issue by croeder** [chrisroederucdenver/CCDA_OMOP_by_Python#16]
sometimes you get data found under different paths for different documents. Need to come up with a way to specify two fields bu only have one of them appear, whichever one has data, and have them both have the same name.

One idea is give the a sequence number in addition to the main name, the use a derivation to order them and pick the first non-null version.

It might be nice to just specify a prioirity number on fields with the same name, but not having unique keys in hte field ie sketchy. The first keeps the code simple. The second more directly specifies what is to be achieved.

**Comment by chrisroederucdenver** [comment]
WIP on branch multiple_fields_priority_16

**Comment by chrisroederucdenver** [comment]
done with ed062b725d3f34c656ca0488a34e3e153c2fd4b3

**Comment by chrisroederucdenver** [comment]
Duplicate of #83
