### ISSUE TITLE
anna_flux has little output

### ISSUE THREAD

**Issue by chrisroederucdenver** [chrisroederucdenver/CCDA_OMOP_by_Python#33]
I've skimmed it quickly and found lots of empty sections, we need to be clear that the empty output is not from bad code, but from empty data. We need to identify the source and watch out for more like this.

seen in anna_flux.xml, also healtheconnectak-ccd-20210226.2.xml.
NB, IIRC they are very different files!!

**Comment by AdamLeeIT** [comment]
Checked out anna_flux.xml example. It is a valid CCD as 
Our first valid templates are:
2.16.840.1.113883.10.20.22.1.1 - USRealmHeaderV3
2.16.840.1.113883.10.20.22.1.2 - ContinuityofCareDocumentCCDV3
which we would expect with most all of our CCDs.

We should discover the following sections (names may be different but OIDs same):
2.16.840.1.113883.10.20.22.2.4.1 - VitalSignsSectionentriesrequiredV3 - Empty
2.16.840.1.113883.10.20.22.2.17 - SocialHistorySectionV3 - Empty
2.16.840.1.113883.10.20.22.2.3.1 - ResultsSectionentriesrequiredV3 - Empty
2.16.840.1.113883.10.20.22.2.1.1 - MedicationsSectionentriesrequiredV2 - Empty
2.16.840.1.113883.10.20.22.2.6.1 - AllergiesandIntolerancesSectionentriesrequiredV3 - Empty
2.16.840.1.113883.10.20.22.2.5.1 - ProblemSectionentriesrequiredV3 - Not Empty
2.16.840.1.113883.10.20.22.2.9 - AssessmentandPlanSectionV2 - Not Empty

This puts us in a interesting call about reading the <section> element nullFlavor attribute prior to parsing the section. If 'NI' or perhaps present at all, then treat the section as empty. Of course if we only target sections with <entry> tags, then this rule is implicitly enforced.

An argument against looking for entry elements could be Assessment and Plan Section [https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.9.html] that MAY include a entry, but requires text elements. In short, the Assessment and Plan Section is not scoped to map to OMOP, but a example nonetheless.

**Resolution**
Open issue for adding rule to codebase for section nullFlavor="NI" example '<section nullFlavor="NI" classCode="DOCSECT" moodCode="EVN">'

**Comment by chrisroederucdenver** [comment]
I'm not surprised anna_flux.xml is well-formed. I wanted to verify my read that it is mostly empty. We need to make note of its source and keep an eye out for more files from that source that are basically empty. 

What do you mean "discover the following sections"?  do you mean we should include those sections in our configuration, in the metadata.py? Yes.
I recognize the names, but lost sight of the Sections that have Required or not in them.
SocialHistory, Allergies and AssementPlan are further down the list.

**ProblemSectionentriesrequired  should be considered part of ProblemSections for condition_occurrence and is a legitimate short-term TODO.**  ...I'll enter an issue ticket for that.

Can you provide more example detail about nullFlavor or NI??? I don't understand which rule you mean to reference when you say "this rules is implicitly enforced".

I didn't immediately recognize "entry" elements, but did when you mentioned them in contrast to text elements. If there's an XML element (section or entry...) that is on our list and doesn't require entries, there's no harm in trying to harvest data from the entry, regardless if it requires text. XML text elements are out of scope.

**Comment by AdamLeeIT** [comment]
Reading XML text elements are out of scope is a good thing to read.
The entry element should be present if something is indeed coded. For sections like VitalSignsSectionentriesrequired the <entry> element is quite literally required and what we'd parse to get into OMOP. The nullFlavor attribute on the section is mutually exclusive with entries on the entriesRequired sections. It may be nothing to code or resolve, but note in our documentation that we understand the behavior. By 'implictly enforced' I mean if we look for <entry> element children after identifying a templateID OID, and we have 0 entries then we can infer/imply/assume there is No information aka NI

Problem Section (entries required)
MAY contain zero or one [0..1] @nullFlavor="NI" No information 
If section/@nullFlavor is not present:
SHALL contain at least one [1..*] entry

**Comment by chrisroederucdenver** [comment]
I had seen some sections come in pairs, X and Xrequired.
It must be a fair guess that X might have an NI, and Xrequired shouldn’t.
The point for our code is to use both templateIDs.

From: Adam Lee ***@***.***>
Date: Tuesday, August 13, 2024 at 7:16 AM
To: chrisroederucdenver/CCDA_OMOP_by_Python ***@***.***>
Cc: Chris Roeder CUAnschutz ***@***.***>, Author ***@***.***>
Subject: Re: [chrisroederucdenver/CCDA_OMOP_by_Python] anna_flux has little output (Issue #33)

Reading XML text elements are out of scope is a good thing to read.
The entry element should be present if something is indeed coded. For sections like VitalSignsSectionentriesrequired the element is quite literally required and what we'd parse to get into OMOP. The nullFlavor attribute on the section is mutually exclusive with entries on the entriesRequired sections. It may be nothing to code or resolve, but note in our documentation that we understand the behavior. By 'implictly enforced' I mean if we look for element children after identifying a templateID OID, and we have 0 entries then we can infer/imply/assume there is No information aka NI

Problem Section (entries required)
MAY contain zero or one [0..1] @nullFlavor<https://github.com/nullFlavor>="NI" No information
If ***@***.***<https://github.com/nullFlavor> is not present:
SHALL contain at least one [1..*] entry

**Comment by chrisroederucdenver** [comment]
BTW, bennis_shauna_ccda.xml also has elements with nullFlavor="OTH" (not NI) and are followed by a <translation> element with code and codeSystem attributes. healtheconnectak-ccd-20210226.2.xml, eHX_Terry.xml, as well.

Patient-502 appears to use translations as ways of specifying the term in other vocabularies. This can be seen in C-CDA_R2-1_CCD.xml too.
