### ISSUE TITLE
Prep for Demos 8/14 and September

### ISSUE THREAD

**Issue by croeder** [chrisroederucdenver/CCDA_OMOP_by_Python#49]
things to show
- Review the XML files and XPath
- Show metadata.py
  - basic idea of extracting values and routing to OMOP
  - PK and FK, and open questoins about where we don't have PKs
  - DERIVED fields
  - DOMAIN fields
 - ON-GOING evaluation of rules to different documents. 
   - task matrix
   - "ERRORS" these are where the rules either fail or the documents fail the rules.

**Comment by chrisroederucdenver** [comment]
8/14 cancelled. 
We'll worry about September as it draws nearer.
